services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    environment:
       POSTGRES_USER: Ale
       POSTGRES_PASSWORD: FeryAle12
       POSTGRES_DB: school
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    container_name: nextjs_app
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL: postgresql://Ale:FeryAle12@postgres:5432/school
    depends_on:
      - postgres
volumes:
  pgdata: