-- CreateEnum
CREATE TYPE "RESULT" AS ENUM ('TUGAS_HARIAN', 'TUGAS_AKHIR', 'PEKERJAAN_RUMAH', 'UJIAN_TENGAH_SEMESTER', 'UJIAN_AKHIR_SEMESTER');

-- AlterTable
ALTER TABLE "Result" ADD COLUMN     "resultType" "RESULT";
